name: Run SHE 247 Python App

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file"

      - name: Run SHE 247 App
        run: |
          python main.py
